    // ========= DATA: STORES =========
    const stores = [
      {
        id: "1",
        name: "Rapture Photo",
        category: "Tecnología",
        categoryKey: "tecnologia",
        extra: "Local 101",
        link: "https://onettohector.github.io/TP-LOCAL-COMERCIAL-2/",
        position: { top: "43%", left: "35%" },
      },
      {
        id: "2",
        name: "Soledad",
        category: "Moda",
        categoryKey: "moda",
        link: "https://micaela7.github.io/LOCAL-COMERCIAL-FINAL/",
        extra: "Local 215",
        position: { top: "43%", left: "78%" },
      },
      {
        id: "3",
        name: "Fullgarden",
        category: "Tecnología",
        categoryKey: "tecnologia",
        link: "https://mmarcano-uade.github.io/TiendaComponentesDePC",
        extra: "Local 320",
        position: { top: "81%", left: "55%" },
      },
      {
        id: "4",
        name: "Aruma home",
        category: "Hogar",
        categoryKey: "hogar",
        link: "https://denisemazur16.github.io/Mi-Local-Aruma-Home-2.0/",
        extra: "Local 08",
        position: { top: "43%", left: "55%" },
      },
    {
        id: "5",
        name: "Baños",
        category: "banos",
        categoryKey: "banos",
        extra: "Local 145",
        position: { top: "80%", left: "80%" },
      },
          {
        id: "6",
        name: "Entrada Estacionamiento",
        category: "estacionamiento",
        categoryKey: "estacionamiento",
        extra: "Local 145",
        position: { top: "13%", left: "13%" },
      },
{
        id: "7",
        name: "Guarderia",
        category: "guarderia",
        categoryKey: "guarderia",
        extra: "Local 145",
        position: { top: "43%", left: "13%" },
      },
      {
        id: "8",
        name: "Area de descanso",
        category: "guarderia",
        categoryKey: "guarderia",
        extra: "Local 145",
        position: { top: "81%", left: "13%" },
      },
      {
        id: "9",
        name: "Cines",
        category: "cine",
        categoryKey: "cine",
        extra: "Local 145",
        position: { top: "13%", left: "30%" },
      },
            {
        id: "10",
        name: "Feria de comida",
        category: "gastronomia",
        categoryKey: "gastronomia",
        extra: "Local 145",
        position: { top: "81%", left: "35%" },
      },
    ];
