    // ========= DATA: STORES =========
    const stores = [
      {
        id: "1",
        name: "Rapture Photo",
        category: "Tecnología",
        categoryKey: "tecnologia",
        extra: "Local 101",
        link: "https://onettohector.github.io/TP-LOCAL-COMERCIAL-2/",
        position: { top: "43%", left: "35%" },
      },
      {
        id: "2",
        name: "Soledad",
        category: "Moda",
        categoryKey: "moda",
        link: "https://onettohector.github.io/TP-LOCAL-COMERCIAL-2/",
        extra: "Local 215",
        position: { top: "43%", left: "78%" },
      },
      {
        id: "3",
        name: "Fullgarden",
        category: "Tecnología",
        categoryKey: "tecnologia",
        link: "https://mmarcano-uade.github.io/TiendaComponentesDePC",
        extra: "Local 320",
        position: { top: "81%", left: "55%" },
      },
      {
        id: "4",
        name: "Aruma home",
        category: "Hogar",
        categoryKey: "hogar",
        link: "https://denisemazur16.github.io/Aruma-Home-2.0/",
        extra: "Local 08",
        position: { top: "43%", left: "55%" },
      },
      {
        id: "5",
        name: "NOMBRE 5",
        category: "Moda",
        categoryKey: "moda",
        extra: "Local 145",
        position: { top: "81%", left: "35%" },
      },
    ];
